#Functions for interacting with database
from . import tables

#creates a new question in the database
def create_question(db, topic, userCreated, overview, title, options, correct_answer_id, explanation):
    #creates a question object representing one row
    db_question = tables.Questions(
        topic = topic,
        userCreated = userCreated,
        overview = overview,
        title = title,
        options = options,
        correct_answer_id = correct_answer_id,
        explanation = explanation,
    )
    #Adds the new question to the database
    db.add(db_question)
    db.commit()
    #Reloads db_question object which populates fields that were autogenerated
    db.refresh(db_question)
    return db_question

#Gets all questions created by a user(id)
def get_all_user_questions(db, id):
    return db.query(tables.Questions).filter(tables.Questions.userCreated == id).all()

#Delete all questions create by user(id)
def delete_history_for_user(db, id):
    db.query(tables.Questions).filter(tables.Questions.userCreated == id).delete()
    db.commit()